# Generated by Django 3.0.4 on 2020-04-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=200)),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econex.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OsveshModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('light', models.IntegerField()),
                ('efficincy', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econex.Seria')),
            ],
        ),
    ]
