# Generated by Django 3.0.4 on 2020-04-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seria',
            name='catogory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='econex.Category'),
        ),
    ]
