# Generated by Django 3.0.4 on 2020-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econex', '0003_auto_20200405_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='seria',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
