# Generated by Django 3.0.4 on 2020-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econex', '0004_seria_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
