# Generated by Django 3.0.4 on 2020-04-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econex', '0005_category_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
