# Generated by Django 3.0.4 on 2020-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econex', '0006_auto_20200405_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seria',
            name='desc',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seria',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
