# Generated by Django 3.0.4 on 2020-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econex', '0007_auto_20200405_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seria',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
